### ISSUE TITLE
EPIC: Get Findr to the point where it is easily reusable

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/findr#19]
Task Brainstorming:
- [ ] make findr-mui headless
  - [ ] convert to mui-less
  - [ ] move to findr-react
- [ ] styleguidist demos
- [ ] each package has its own fully doc'd readme 
- [ ] 

Previous Checklist: https://docs.google.com/document/d/1TA8iGRChZHwLuPxHVH-iP-anR5zPbtG2_6QQnkBYbv0/edit#heading=h.63e0dts1qxai

**Comment by jincypjose** [comment]
Sample readme - [Blank_readme (3).md](https://github.com/unfoldingWord/findr/files/12280428/Blank_readme.3.md)

**Comment by PhotoNomad0** [comment]
Here is an RCL with typescript: https://github.com/unfoldingWord/single-scripture-rcl

**Comment by PhotoNomad0** [comment]
Also translationCore uses jsdocs: https://github.com/unfoldingWord/translationCore/blob/develop/package.json#L38

**Comment by theNerd247** [comment]
@kintsoogi created https://www.notion.so/unfoldingword/Improving-Findr-Readability-3e7db78c4df84b2a8397124a76f588ca#f2869d17223545d18d07ca2a91c48ed8 for comments on findr
